#!/bin/bash

YCSB=ycsb-0.17.0
YCSB_JDBC_LIB=${YCSB}/jdbc-binding/lib

MYSQL_CONNECTOR=mysql-connector-java-8.0.30.jar

if [ ! -f ${MYSQL_CONNECTOR} ]; then
  echo "${MYSQL_CONNECTOR} is not found"
  exit
fi

if [ ! -d ${YCSB} ]; then
  wget https://github.com/brianfrankcooper/YCSB/releases/download/0.17.0/${YCSB}.tar.gz
  tar xvfx ${YCSB}.tar.gz
fi

if [ ! -f ${YCSB_JDBC_LIB}/${MYSQL_CONNECTOR} ]; then
  cp ${MYSQL_CONNECTOR} ${YCSB_JDBC_LIB}
fi

export YCSB_ROOT=`pwd`/${YCSB}
export YCSB_DB_PROPERTIES=`pwd`/mysqltest/ycsb/db.properties

echo "YCSB_ROOT          : ${YCSB_ROOT}"
echo "YCSB_DB_PROPERTIES : ${YCSB_DB_PROPERTIES}"
echo "MYSQL_CONNECTOR    : ${YCSB_JDBC_LIB}/${MYSQL_CONNECTOR}"